{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 3",
      "release_date": "2009-07-27T00:00:00Z",
      "advisory": "RHSA-2009:1178",
      "package": "python-0:2.2.3-6.11",
      "cpe": "cpe:/o:redhat:enterprise_linux:3"
    },
    {
      "product_name": "Red Hat Enterprise Linux 4",
      "release_date": "2009-07-27T00:00:00Z",
      "advisory": "RHSA-2009:1177",
      "package": "python-0:2.3.4-14.7.el4_8.2",
      "cpe": "cpe:/o:redhat:enterprise_linux:4"
    }
  ],
  "package_state": null,
  "threat_severity": "Low",
  "public_date": "2008-03-29T00:00:00Z",
  "bugzilla": {
    "description": "imageop module integer overflows",
    "id": "441306",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=441306"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-190",
  "statement": "",
  "acknowledgement": "Red Hat would like to thank David Remahl (Apple Product Security team) for reporting this issue.",
  "name": "CVE-2008-1679",
  "document_distribution": "",
  "details": [
    "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2008-1679\nhttps://nvd.nist.gov/vuln/detail/CVE-2008-1679"
  ]
}