{
  "Class": "vulnerability",
  "ID": "oval:com.redhat.cve:def:202029651",
  "Version": "636",
  "Metadata": {
    "Title": "CVE-2020-29651 python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality (low)",
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2020-29651",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2020-29651"
      }
    ],
    "Description": "DOCUMENTATION: The MITRE CVE dictionary describes this issue as: A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality. \n            STATEMENT: In Red Hat OpenStack Platform, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-py package.",
    "Advisory": {
      "From": "secalert@redhat.com",
      "Severity": "Low",
      "Issued": {},
      "Updated": {
        "Date": "2021-10-28"
      },
      "Cves": [
        {
          "CveID": "CVE-2020-29651",
          "Cvss3": "4.3/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
          "Cwe": "CWE-20-\u003eCWE-400",
          "Impact": "low",
          "Href": "https://access.redhat.com/security/cve/CVE-2020-29651",
          "Public": "20200903"
        }
      ],
      "AffectedCpeList": [
        "cpe:/a:redhat:enterprise_linux:8",
        "cpe:/a:redhat:enterprise_linux:8::appstream",
        "cpe:/a:redhat:enterprise_linux:8::crb",
        "cpe:/a:redhat:enterprise_linux:8::highavailability",
        "cpe:/a:redhat:enterprise_linux:8::nfv",
        "cpe:/a:redhat:enterprise_linux:8::realtime",
        "cpe:/a:redhat:enterprise_linux:8::resilientstorage",
        "cpe:/a:redhat:enterprise_linux:8::sap",
        "cpe:/a:redhat:enterprise_linux:8::sap_hana",
        "cpe:/a:redhat:enterprise_linux:8::supplementary",
        "cpe:/o:redhat:enterprise_linux:8",
        "cpe:/o:redhat:enterprise_linux:8::baseos"
      ],
      "Affected": {
        "Resolution": {
          "State": "Will not fix"
        }
      }
    }
  },
  "Criteria": {
    "Operator": "OR",
    "Criterions": [
      {
        "Comment": "Red Hat Enterprise Linux must be installed",
        "TestRef": "oval:com.redhat.cve:tst:20052541004"
      }
    ],
    "Criterias": [
      {
        "Operator": "AND",
        "Criterions": [
          {
            "Comment": "Red Hat Enterprise Linux 8 is installed",
            "TestRef": "oval:com.redhat.cve:tst:20052541003"
          }
        ],
        "Criterias": [
          {
            "Operator": "OR",
            "Criterias": [
              {
                "Operator": "AND",
                "Criterions": [
                  {
                    "Comment": "python38-py is installed",
                    "TestRef": "oval:com.redhat.cve:tst:202029651001"
                  },
                  {
                    "Comment": "python38-py is signed with Red Hat redhatrelease2 key",
                    "TestRef": "oval:com.redhat.cve:tst:202029651002"
                  }
                ]
              },
              {
                "Operator": "AND",
                "Criterions": [
                  {
                    "Comment": "python2-py is installed",
                    "TestRef": "oval:com.redhat.cve:tst:202029651003"
                  },
                  {
                    "Comment": "python2-py is signed with Red Hat redhatrelease2 key",
                    "TestRef": "oval:com.redhat.cve:tst:202029651004"
                  }
                ]
              },
              {
                "Operator": "AND",
                "Criterions": [
                  {
                    "Comment": "python39-py is installed",
                    "TestRef": "oval:com.redhat.cve:tst:202029651005"
                  },
                  {
                    "Comment": "python39-py is signed with Red Hat redhatrelease2 key",
                    "TestRef": "oval:com.redhat.cve:tst:202029651006"
                  }
                ]
              },
              {
                "Operator": "AND",
                "Criterions": [
                  {
                    "Comment": "python-py is installed",
                    "TestRef": "oval:com.redhat.cve:tst:202029651007"
                  },
                  {
                    "Comment": "python-py is signed with Red Hat redhatrelease2 key",
                    "TestRef": "oval:com.redhat.cve:tst:202029651008"
                  }
                ]
              },
              {
                "Operator": "AND",
                "Criterions": [
                  {
                    "Comment": "Module python27:2.7 is enabled",
                    "TestRef": "oval:com.redhat.cve:tst:20074559114"
                  }
                ],
                "Criterias": [
                  {
                    "Operator": "OR",
                    "Criterias": [
                      {
                        "Operator": "AND",
                        "Criterions": [
                          {
                            "Comment": "python38-py is installed",
                            "TestRef": "oval:com.redhat.cve:tst:202029651001"
                          },
                          {
                            "Comment": "python38-py is signed with Red Hat redhatrelease2 key",
                            "TestRef": "oval:com.redhat.cve:tst:202029651002"
                          }
                        ]
                      },
                      {
                        "Operator": "AND",
                        "Criterions": [
                          {
                            "Comment": "python2-py is installed",
                            "TestRef": "oval:com.redhat.cve:tst:202029651003"
                          },
                          {
                            "Comment": "python2-py is signed with Red Hat redhatrelease2 key",
                            "TestRef": "oval:com.redhat.cve:tst:202029651004"
                          }
                        ]
                      },
                      {
                        "Operator": "AND",
                        "Criterions": [
                          {
                            "Comment": "python39-py is installed",
                            "TestRef": "oval:com.redhat.cve:tst:202029651005"
                          },
                          {
                            "Comment": "python39-py is signed with Red Hat redhatrelease2 key",
                            "TestRef": "oval:com.redhat.cve:tst:202029651006"
                          }
                        ]
                      },
                      {
                        "Operator": "AND",
                        "Criterions": [
                          {
                            "Comment": "python-py is installed",
                            "TestRef": "oval:com.redhat.cve:tst:202029651007"
                          },
                          {
                            "Comment": "python-py is signed with Red Hat redhatrelease2 key",
                            "TestRef": "oval:com.redhat.cve:tst:202029651008"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}