{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4",
      "fix_state": "Affected",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:openshift:4"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Out of support scope",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Affected",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "fix_state": "Affected",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:openstack:16.2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.0",
      "fix_state": "Affected",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:openstack:17.0"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Affected",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Affected",
      "package_name": "python-sqlparse",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-04-19T00:00:00Z",
  "bugzilla": {
    "description": "Parser contains a regular expression that is vulnerable to ReDOS (Regular Expression Denial of Service)",
    "id": "2187903",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2187903"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-1333",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-30608",
  "document_distribution": "",
  "details": [
    "sqlparse is a non-validating SQL parser module for Python. In affected versions the SQL parser contains a regular expression that is vulnerable to ReDoS (Regular Expression Denial of Service). This issue was introduced by commit `e75e358`. The vulnerability may lead to Denial of Service (DoS). This issues has been fixed in sqlparse 0.4.4 by commit `c457abd5f`. Users are advised to upgrade. There are no known workarounds for this issue.",
    "A flaw was found in sqlparse. The SQL parser contains a regular expression vulnerable to a Regular Expression Denial of Service (ReDoS). The vulnerability may lead to a denial of service (DoS)."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-30608\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-30608\nhttps://github.com/andialbrecht/sqlparse/security/advisories/GHSA-rrm6-wvj7-cwh2"
  ]
}