{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Will not fix",
      "package_name": "python-suds",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Will not fix",
      "package_name": "python-suds",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Will not fix",
      "package_name": "python-suds",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2013-06-27T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2013-2217 python-suds: Insecure temporary directory use when initializing file-based URL cache",
    "id": "978696",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=978696"
  },
  "cvss": {
    "cvss_base_score": "1.9",
    "cvss_scoring_vector": "AV:L/AC:M/Au:N/C:N/I:P/A:N",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-377",
  "statement": "This issue affects the version of python-suds as shipped with Red Hat Enterprise Linux 5 and 6. The Red Hat Security Response Team has rated this issue as having low security impact, a future update may address this flaw.",
  "acknowledgement": "",
  "name": "CVE-2013-2217",
  "document_distribution": "",
  "details": [
    "cache.py in Suds 0.4, when tempdir is set to None, allows local users to redirect SOAP queries and possibly have other unspecified impact via a symlink attack on a cache file with a predictable name in /tmp/suds/."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2013-2217\nhttps://nvd.nist.gov/vuln/detail/CVE-2013-2217"
  ]
}