{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "pyOpenSSL",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "pyOpenSSL",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "pyOpenSSL",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 4",
      "fix_state": "Not affected",
      "package_name": "pyOpenSSL",
      "cpe": "cpe:/a:redhat:openstack:4"
    },
    {
      "product_name": "Red Hat Storage 2.1",
      "fix_state": "Not affected",
      "package_name": "pyOpenSSL",
      "cpe": "cpe:/a:redhat:storage:2.1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2013-09-04T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2013-4314 pyOpenSSL: hostname check bypassing vulnerability",
    "id": "1005325",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1005325"
  },
  "cvss": {
    "cvss_base_score": "4.3",
    "cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "Not vulnerable. This issue did not affect the versions of pyOpenSSL as shipped with Red Hat Enterprise Linux 5 and 6.",
  "acknowledgement": "",
  "name": "CVE-2013-4314",
  "document_distribution": "",
  "details": [
    "The X509Extension in pyOpenSSL before 0.13.1 does not properly handle a '\\0' character in a domain name in the Subject Alternative Name field of an X.509 certificate, which allows man-in-the-middle attackers to spoof arbitrary SSL servers via a crafted certificate issued by a legitimate Certification Authority."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2013-4314\nhttps://nvd.nist.gov/vuln/detail/CVE-2013-4314"
  ]
}