{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "OpenShift Enterprise 1",
      "fix_state": "Will not fix",
      "package_name": "python-virtualenv",
      "cpe": "cpe:/a:redhat:openshift:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Affected",
      "package_name": "python-setuptools",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Affected",
      "package_name": "python-setuptools",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python-setuptools",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python-virtualenv",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise MRG 1",
      "fix_state": "Will not fix",
      "package_name": "python-setuptools",
      "cpe": "cpe:/a:redhat:enterprise_mrg:1"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "python27-python-setuptools",
      "cpe": "cpe:/a:redhat:rhel_software_collections:1"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "python27-python-virtualenv",
      "cpe": "cpe:/a:redhat:rhel_software_collections:1"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "python33-python-setuptools",
      "cpe": "cpe:/a:redhat:rhel_software_collections:1"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "python33-python-virtualenv",
      "cpe": "cpe:/a:redhat:rhel_software_collections:1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2013-06-02T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2013-1633 python-setuptools: easy_install insecure installation mechanism",
    "id": "994182",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=994182"
  },
  "cvss": {
    "cvss_base_score": "4.4",
    "cvss_scoring_vector": "AV:L/AC:M/Au:N/C:P/I:P/A:P",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "Red Hat OpenShift Enterprise 1.2 is now in Production 1 Phase of the support and maintenance life cycle. This has been rated as having Moderate security impact and is not currently planned to be addressed in future updates. For additional information, refer to the Red Hat OpenShift Enterprise Life Cycle: https://access.redhat.com/site/support/policy/updates/openshift.",
  "acknowledgement": "",
  "name": "CVE-2013-1633",
  "document_distribution": "",
  "details": [
    "easy_install in setuptools before 0.7 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to the default use of the product."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2013-1633\nhttps://nvd.nist.gov/vuln/detail/CVE-2013-1633"
  ]
}